### ISSUE TITLE
Wrong File IO mode

### ISSUE THREAD

**Issue by J0las** [THI-Drone/mission_control_package#6]
Die Datei mit dem JSON sollte Read Only geöffnet werden.
https://github.com/THI-Drone/mission_control_package/blob/e10330a98e4b4d55e7f563f512f1680a0daef974/src/mission_definition_file.cpp#L20
```c++
    file.open(file_path, std::ios::in);
``` 

Ich weiß da gibt es keinen PR, der Issue ist nur, damit ich das nicht vergesse.
https://en.cppreference.com/w/cpp/io/basic_ifstream/open

**Comment by Philipp66904** [comment]
Ups, ja da bin ich wohl in der Zeile der Doku verrutscht 😅
